name: giphy_selector
description: Pick a GIPHY GIF, Sticker or Emoji
version: 1.0.0
homepage: https://github.com/amantoux/giphy_selector


environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_staggered_grid_view: ^0.6.0
  http: ^0.13.3
  url_launcher: ^6.1.6


dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints:
  mockito: ^5.0.7
  pedantic: ^1.11.0
  matcher: ^0.12.10

flutter:
  assets:
    - assets/img/
